import { z } from "incur";
import { createClient, type HttpMethod } from "./client.js";
import { parseJsonObject, parseJsonValue } from "./json.js";

export type ApiOperation = {
  command: string;
  group: string;
  method: HttpMethod;
  path: string;
  summary: string;
};

export const operations = [
  {
    group: "server",
    command: "restart",
    method: "PUT",
    path: "/api/server/restart",
    summary: "Restart the Homebridge instance.",
  },
  {
    group: "server",
    command: "restart-child",
    method: "PUT",
    path: "/api/server/restart/{deviceId}",
    summary: "Restart a child bridge instance.",
  },
  {
    group: "server",
    command: "stop-child",
    method: "PUT",
    path: "/api/server/stop/{deviceId}",
    summary: "Stop a child bridge instance.",
  },
  {
    group: "server",
    command: "start-child",
    method: "PUT",
    path: "/api/server/start/{deviceId}",
    summary: "Start a child bridge instance.",
  },
  {
    group: "server",
    command: "pairing",
    method: "GET",
    path: "/api/server/pairing",
    summary: "Get Homebridge/HomeKit pairing information.",
  },
  {
    group: "server",
    command: "reset-accessory",
    method: "PUT",
    path: "/api/server/reset-homebridge-accessory",
    summary:
      "Reset the main Homebridge bridge, username, pin, cached bridges, and cached accessories.",
  },
  {
    group: "server",
    command: "reset-cached-accessories",
    method: "PUT",
    path: "/api/server/reset-cached-accessories",
    summary: "Remove Homebridge cached accessories.",
  },
  {
    group: "server",
    command: "cached-accessories",
    method: "GET",
    path: "/api/server/cached-accessories",
    summary: "List cached Homebridge accessories.",
  },
  {
    group: "server",
    command: "delete-cached-accessories",
    method: "DELETE",
    path: "/api/server/cached-accessories",
    summary: "Remove multiple Homebridge cached accessories.",
  },
  {
    group: "server",
    command: "delete-cached-accessory",
    method: "DELETE",
    path: "/api/server/cached-accessories/{uuid}",
    summary: "Remove a single Homebridge cached accessory.",
  },
  {
    group: "server",
    command: "pairings",
    method: "GET",
    path: "/api/server/pairings",
    summary: "List all paired accessories.",
  },
  {
    group: "server",
    command: "delete-pairings",
    method: "DELETE",
    path: "/api/server/pairings",
    summary: "Remove multiple paired bridges.",
  },
  {
    group: "server",
    command: "pairing-by-id",
    method: "GET",
    path: "/api/server/pairings/{deviceId}",
    summary: "Get a single device pairing.",
  },
  {
    group: "server",
    command: "delete-pairing",
    method: "DELETE",
    path: "/api/server/pairings/{deviceId}",
    summary: "Remove a single paired bridge.",
  },
  {
    group: "server",
    command: "delete-device-accessories",
    method: "DELETE",
    path: "/api/server/pairings/{deviceId}/accessories",
    summary: "Remove a paired bridge's cached accessories.",
  },
  {
    group: "server",
    command: "delete-devices-accessories",
    method: "DELETE",
    path: "/api/server/pairings/accessories",
    summary: "Remove multiple paired bridges' cached accessories.",
  },
  {
    group: "server",
    command: "unused-port",
    method: "GET",
    path: "/api/server/port/new",
    summary: "Return a random unused port.",
  },
  {
    group: "server",
    command: "system-network-interfaces",
    method: "GET",
    path: "/api/server/network-interfaces/system",
    summary: "Return available server network interfaces.",
  },
  {
    group: "server",
    command: "network-interfaces",
    method: "GET",
    path: "/api/server/network-interfaces/bridge",
    summary: "Return Homebridge network interfaces.",
  },
  {
    group: "server",
    command: "set-network-interfaces",
    method: "PUT",
    path: "/api/server/network-interfaces/bridge",
    summary: "Set Homebridge network interfaces.",
  },
  {
    group: "server",
    command: "mdns-advertiser",
    method: "GET",
    path: "/api/server/mdns-advertiser",
    summary: "Return mDNS advertiser settings.",
  },
  {
    group: "server",
    command: "set-mdns-advertiser",
    method: "PUT",
    path: "/api/server/mdns-advertiser",
    summary: "Set mDNS advertiser settings.",
  },
  {
    group: "server",
    command: "set-name",
    method: "PUT",
    path: "/api/server/name",
    summary: "Set the Homebridge name.",
  },
  {
    group: "server",
    command: "port",
    method: "GET",
    path: "/api/server/port",
    summary: "Get the Homebridge port.",
  },
  {
    group: "server",
    command: "set-port",
    method: "PUT",
    path: "/api/server/port",
    summary: "Set the Homebridge port.",
  },
  {
    group: "server",
    command: "ports",
    method: "GET",
    path: "/api/server/ports",
    summary: "Get usable ports from config.",
  },
  {
    group: "server",
    command: "set-ports",
    method: "PUT",
    path: "/api/server/ports",
    summary: "Update usable Homebridge ports.",
  },
  {
    group: "server",
    command: "upload-wallpaper",
    method: "POST",
    path: "/api/server/wallpaper",
    summary: "Upload a wallpaper image.",
  },
  {
    group: "server",
    command: "delete-wallpaper",
    method: "DELETE",
    path: "/api/server/wallpaper",
    summary: "Delete the current wallpaper.",
  },
  {
    group: "config",
    command: "get",
    method: "GET",
    path: "/api/config-editor",
    summary: "Return the current Homebridge config.json.",
  },
  {
    group: "config",
    command: "update",
    method: "POST",
    path: "/api/config-editor",
    summary: "Update the Homebridge config.json.",
  },
  {
    group: "config",
    command: "plugin",
    method: "GET",
    path: "/api/config-editor/plugin/{pluginName}",
    summary: "Return config blocks for a plugin.",
  },
  {
    group: "config",
    command: "update-plugin",
    method: "POST",
    path: "/api/config-editor/plugin/{pluginName}",
    summary: "Replace config blocks for a plugin.",
  },
  {
    group: "config",
    command: "disable-plugin",
    method: "PUT",
    path: "/api/config-editor/plugin/{pluginName}/disable",
    summary: "Mark a plugin as disabled.",
  },
  {
    group: "config",
    command: "enable-plugin",
    method: "PUT",
    path: "/api/config-editor/plugin/{pluginName}/enable",
    summary: "Mark a plugin as enabled.",
  },
  {
    group: "config",
    command: "set-ui",
    method: "PUT",
    path: "/api/config-editor/ui",
    summary: "Update a Homebridge UI config property.",
  },
  {
    group: "config",
    command: "set-accessory-blacklist",
    method: "PUT",
    path: "/api/config-editor/ui/accessory-control/instance-blacklist",
    summary: "Update the accessory control instance blacklist.",
  },
  {
    group: "config",
    command: "hide-plugin-updates",
    method: "PUT",
    path: "/api/config-editor/ui/plugins/hide-updates-for",
    summary: "Update hidden plugin update notices.",
  },
  {
    group: "config",
    command: "backups",
    method: "GET",
    path: "/api/config-editor/backups",
    summary: "List config backups.",
  },
  {
    group: "config",
    command: "delete-backups",
    method: "DELETE",
    path: "/api/config-editor/backups",
    summary: "Delete all config backups.",
  },
  {
    group: "config",
    command: "backup",
    method: "GET",
    path: "/api/config-editor/backups/{backupId}",
    summary: "Return a config backup.",
  },
  {
    group: "plugins",
    command: "list",
    method: "GET",
    path: "/api/plugins",
    summary: "List installed Homebridge plugins.",
  },
  {
    group: "plugins",
    command: "search",
    method: "GET",
    path: "/api/plugins/search/{query}",
    summary: "Search NPM for Homebridge plugins.",
  },
  {
    group: "plugins",
    command: "lookup",
    method: "GET",
    path: "/api/plugins/lookup/{pluginName}",
    summary: "Lookup a plugin on NPM.",
  },
  {
    group: "plugins",
    command: "versions",
    method: "GET",
    path: "/api/plugins/lookup/{pluginName}/versions",
    summary: "Get plugin versions and tags.",
  },
  {
    group: "plugins",
    command: "schema",
    method: "GET",
    path: "/api/plugins/config-schema/{pluginName}",
    summary: "Get a plugin config.schema.json.",
  },
  {
    group: "plugins",
    command: "changelog",
    method: "GET",
    path: "/api/plugins/changelog/{pluginName}",
    summary: "Get a plugin changelog.",
  },
  {
    group: "plugins",
    command: "release",
    method: "GET",
    path: "/api/plugins/release/{pluginName}",
    summary: "Get plugin release notes.",
  },
  {
    group: "plugins",
    command: "alias",
    method: "GET",
    path: "/api/plugins/alias/{pluginName}",
    summary: "Resolve a plugin type and alias.",
  },
  {
    group: "plugins",
    command: "deconz-dump-file",
    method: "GET",
    path: "/api/plugins/custom-plugins/homebridge-deconz/dump-file",
    summary: "Get homebridge-deconz dump file.",
  },
  {
    group: "plugins",
    command: "hue-dump-file",
    method: "GET",
    path: "/api/plugins/custom-plugins/homebridge-hue/dump-file",
    summary: "Get homebridge-hue dump file.",
  },
  {
    group: "plugins",
    command: "settings-ui-asset",
    method: "GET",
    path: "/api/plugins/settings-ui/{pluginName}/{path}",
    summary: "Return a plugin's custom UI asset.",
  },
  {
    group: "accessories",
    command: "list",
    method: "GET",
    path: "/api/accessories",
    summary: "Return Homebridge accessories.",
  },
  {
    group: "accessories",
    command: "layout",
    method: "GET",
    path: "/api/accessories/layout",
    summary: "Get accessory and room layout.",
  },
  {
    group: "accessories",
    command: "get",
    method: "GET",
    path: "/api/accessories/{uniqueId}",
    summary: "Get and refresh a single accessory.",
  },
  {
    group: "accessories",
    command: "set-characteristic",
    method: "PUT",
    path: "/api/accessories/{uniqueId}",
    summary: "Set an accessory characteristic value.",
  },
  {
    group: "users",
    command: "list",
    method: "GET",
    path: "/api/users",
    summary: "List users.",
  },
  {
    group: "users",
    command: "add",
    method: "POST",
    path: "/api/users",
    summary: "Create a user.",
  },
  {
    group: "users",
    command: "update",
    method: "PATCH",
    path: "/api/users/{userId}",
    summary: "Update a user.",
  },
  {
    group: "users",
    command: "delete",
    method: "DELETE",
    path: "/api/users/{userId}",
    summary: "Delete a user.",
  },
  {
    group: "users",
    command: "change-password",
    method: "POST",
    path: "/api/users/change-password",
    summary: "Update the current user password.",
  },
  {
    group: "users",
    command: "otp-setup",
    method: "POST",
    path: "/api/users/otp/setup",
    summary: "Start 2FA setup.",
  },
  {
    group: "users",
    command: "otp-activate",
    method: "POST",
    path: "/api/users/otp/activate",
    summary: "Activate 2FA.",
  },
  {
    group: "users",
    command: "otp-deactivate",
    method: "POST",
    path: "/api/users/otp/deactivate",
    summary: "Deactivate 2FA.",
  },
  {
    group: "status",
    command: "cpu",
    method: "GET",
    path: "/api/status/cpu",
    summary: "Return CPU load, history, and temperature.",
  },
  {
    group: "status",
    command: "ram",
    method: "GET",
    path: "/api/status/ram",
    summary: "Return memory usage.",
  },
  {
    group: "status",
    command: "network",
    method: "GET",
    path: "/api/status/network",
    summary: "Return network throughput.",
  },
  {
    group: "status",
    command: "uptime",
    method: "GET",
    path: "/api/status/uptime",
    summary: "Return host and UI uptime.",
  },
  {
    group: "status",
    command: "homebridge",
    method: "GET",
    path: "/api/status/homebridge",
    summary: "Return Homebridge status.",
  },
  {
    group: "status",
    command: "child-bridges",
    method: "GET",
    path: "/api/status/homebridge/child-bridges",
    summary: "Return child bridge statuses.",
  },
  {
    group: "status",
    command: "homebridge-version",
    method: "GET",
    path: "/api/status/homebridge-version",
    summary: "Return Homebridge version information.",
  },
  {
    group: "status",
    command: "server",
    method: "GET",
    path: "/api/status/server-information",
    summary: "Return server information.",
  },
  {
    group: "status",
    command: "nodejs",
    method: "GET",
    path: "/api/status/nodejs",
    summary: "Return Node.js version information.",
  },
  {
    group: "status",
    command: "rpi-throttled",
    method: "GET",
    path: "/api/status/rpi/throttled",
    summary: "Return Raspberry Pi throttled status.",
  },
  {
    group: "platform",
    command: "restart-host",
    method: "PUT",
    path: "/api/platform-tools/linux/restart-host",
    summary: "Restart the host server.",
  },
  {
    group: "platform",
    command: "shutdown-host",
    method: "PUT",
    path: "/api/platform-tools/linux/shutdown-host",
    summary: "Shutdown the host server.",
  },
  {
    group: "platform",
    command: "docker-startup-script",
    method: "GET",
    path: "/api/platform-tools/docker/startup-script",
    summary: "Return Docker startup.sh contents.",
  },
  {
    group: "platform",
    command: "update-docker-startup-script",
    method: "PUT",
    path: "/api/platform-tools/docker/startup-script",
    summary: "Update Docker startup.sh contents.",
  },
  {
    group: "platform",
    command: "restart-docker",
    method: "PUT",
    path: "/api/platform-tools/docker/restart-container",
    summary: "Restart the Homebridge Docker container.",
  },
  {
    group: "platform",
    command: "startup-settings",
    method: "GET",
    path: "/api/platform-tools/hb-service/homebridge-startup-settings",
    summary: "Return hb-service startup settings.",
  },
  {
    group: "platform",
    command: "set-startup-settings",
    method: "PUT",
    path: "/api/platform-tools/hb-service/homebridge-startup-settings",
    summary: "Update hb-service startup settings.",
  },
  {
    group: "platform",
    command: "set-full-service-restart-flag",
    method: "PUT",
    path: "/api/platform-tools/hb-service/set-full-service-restart-flag",
    summary: "Request full UI restart next Homebridge restart.",
  },
  {
    group: "platform",
    command: "download-log",
    method: "GET",
    path: "/api/platform-tools/hb-service/log/download",
    summary: "Download the entire log file.",
  },
  {
    group: "platform",
    command: "truncate-log",
    method: "PUT",
    path: "/api/platform-tools/hb-service/log/truncate",
    summary: "Truncate the log file.",
  },
  {
    group: "backup",
    command: "create",
    method: "POST",
    path: "/api/backup",
    summary: "Create a backup in the backup directory.",
  },
  {
    group: "backup",
    command: "download",
    method: "GET",
    path: "/api/backup/download",
    summary: "Download a Homebridge backup tarball.",
  },
  {
    group: "backup",
    command: "next",
    method: "GET",
    path: "/api/backup/scheduled-backups/next",
    summary: "Return next scheduled backup time.",
  },
  {
    group: "backup",
    command: "scheduled",
    method: "GET",
    path: "/api/backup/scheduled-backups",
    summary: "List scheduled backups.",
  },
  {
    group: "backup",
    command: "scheduled-download",
    method: "GET",
    path: "/api/backup/scheduled-backups/{backupId}",
    summary: "Download a scheduled backup.",
  },
  {
    group: "backup",
    command: "delete-scheduled",
    method: "DELETE",
    path: "/api/backup/scheduled-backups/{backupId}",
    summary: "Delete a scheduled backup.",
  },
  {
    group: "backup",
    command: "restore-scheduled",
    method: "POST",
    path: "/api/backup/scheduled-backups/{backupId}/restore",
    summary: "Extract a scheduled backup into the restore directory.",
  },
  {
    group: "backup",
    command: "restore",
    method: "POST",
    path: "/api/backup/restore",
    summary: "Upload a Homebridge backup tarball.",
  },
  {
    group: "backup",
    command: "trigger-restore",
    method: "PUT",
    path: "/api/backup/restore/trigger",
    summary: "Trigger headless restore.",
  },
  {
    group: "backup",
    command: "restore-hbfx",
    method: "POST",
    path: "/api/backup/restore/hbfx",
    summary: "Upload a .hbfx backup.",
  },
  {
    group: "backup",
    command: "restart-after-restore",
    method: "PUT",
    path: "/api/backup/restart",
    summary: "Hard restart after restoring a backup.",
  },
  {
    group: "setup",
    command: "create-first-user",
    method: "POST",
    path: "/api/setup-wizard/create-first-user",
    summary: "Create the first setup wizard user.",
  },
  {
    group: "setup",
    command: "token",
    method: "GET",
    path: "/api/setup-wizard/get-setup-wizard-token",
    summary: "Create a setup wizard auth token.",
  },
] as const satisfies readonly ApiOperation[];

export const groupDescriptions: Record<string, string> = {
  accessories: "Accessory inspection and characteristic updates",
  backup: "Backup and restore commands",
  config: "Homebridge config editor commands",
  platform: "Host, Docker, and hb-service platform tools",
  plugins: "Plugin discovery and plugin metadata commands",
  server: "Homebridge bridge, pairing, port, mDNS, and cache commands",
  setup: "Setup wizard commands",
  status: "Server and Homebridge status commands",
  users: "User and 2FA management commands",
};

export function pathParameterNames(path: string): string[] {
  return [...path.matchAll(/\{([^}]+)\}/g)].map((match) => match[1]);
}

export function fillPath(path: string, args: Record<string, string>): string {
  return path.replace(/\{([^}]+)\}/g, (_, key: string) =>
    encodeURIComponent(args[key] ?? ""),
  );
}

export function createOperationDefinition(operation: ApiOperation) {
  const pathArgs = Object.fromEntries(
    pathParameterNames(operation.path).map((name) => [
      name,
      z.string().describe(`Path parameter: ${name}`),
    ]),
  );
  return {
    args: z.object(pathArgs),
    description: operation.summary,
    options: z.object({
      body: z.string().optional().describe("JSON request body."),
      file: z
        .string()
        .optional()
        .describe("File path to upload as multipart/form-data field `file`."),
      profile: z.string().optional().describe("Credentials profile name."),
      query: z
        .string()
        .optional()
        .describe("JSON object converted to URL query parameters."),
    }),
    async run(c: {
      args: Record<string, string>;
      options: Record<string, string | undefined>;
    }) {
      const client = await createClient({ profileName: c.options.profile });
      return client.request({
        body: parseJsonValue(c.options.body),
        file: c.options.file,
        method: operation.method,
        path: fillPath(operation.path, c.args),
        query: parseJsonObject(c.options.query, "query"),
      });
    },
  };
}
